spring.application.name=esbot

spring.datasource.url=jdbc:postgresql://localhost:5432/esbot
spring.datasource.username=esbot_user
spring.datasource.password=esbot_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
