name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Run Unit Tests
        run: |
          cd application/backend 
          mvn test      
      - name: Run PMD Linter
        run: |
          cd application/backend 
          mvn verify -P pmd-linter
      - name: Run OWASP Dependency Checker
        run: |
          cd application/backend 
          mvn verify -P dependency-check
